CREATE TABLE "users" (
	"id_user" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"surname" text NOT NULL,
	"dni" text NOT NULL,
	"document_type" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"moodle_username" text NOT NULL,
	"moodle_password" text NOT NULL,
	"moodle_id" integer NOT NULL,
	"registration_date" date NOT NULL,
	"nss" text NOT NULL,
	"gender" text NOT NULL,
	"professional_category" text NOT NULL,
	"disability" boolean NOT NULL,
	"terrorism_victim" boolean NOT NULL,
	"gender_violence_victim" boolean NOT NULL,
	"education_level" text NOT NULL,
	"address" text NOT NULL,
	"postal_code" text NOT NULL,
	"city" text NOT NULL,
	"province" text NOT NULL,
	"country" text NOT NULL,
	"observations" text NOT NULL
);
